### ISSUE TITLE
is possible to recquire or release resource set in lua script

### ISSUE THREAD

**Issue by chengyi** [intel/murphy#16]
Hi：
  I want to require or release resource set which created by dbus plugin in lua script
  is there some “offical” way to do this?:rofl:

**Comment by klihub** [comment]
If I understood correctly what you mean (trigger from Lua acquiring or releasing a 'foreign' resource set which was created by a DBus resource client), then I think that is not possible at the moment. The current Lua bindings for resources and resource sets (src/resource/lua-resource.c) only work for resource sets which are created from Lua.

**Comment by ipuustin** [comment]
@chengyi Can you tell a bit what you are doing with Murphy? Maybe we could come up with some advice to help you with your problem.

**Comment by chengyi** [comment]
@ipuustin I am doing audio policy management. I want to make resource set auto be released and acquired according to foreign system events. Thanks for your reply!

**Comment by chengyi** [comment]
> 
> 
> If I understood correctly what you mean (trigger from Lua acquiring or releasing a 'foreign' resource set which was created by a DBus resource client), then I think that is not possible at the moment. The current Lua bindings for resources and resource sets (src/resource/lua-resource.c) only work for resource sets which are created from Lua.

yes, your reply make me believe I already understand the code. :grin:
