### ISSUE TITLE
"offical" way to subscribe events about resource set acquire or release

### ISSUE THREAD

**Issue by chengyi** [intel/murphy#17]
Hi:
  I need to do some actions in domain controller based on the status of specific resource set, I want to do like:

1.  define a table  in lua
2.  update table in resource's veto function
3.  handle the db notification in domain controller

is this way perfect? or we have better solution?

**Comment by klihub** [comment]
I think that is the best/intended way of doing it: administer the conditions you need to act on as data in some table and subscribe to that table from your domain controller.

**Comment by chengyi** [comment]
@klihub got it! thanks:+1:
