### ISSUE TITLE
is possible to be notified with the updated row instead of the whole table

### ISSUE THREAD

**Issue by chengyi** [intel/murphy#28]
Hi:
I found that when a table got updated, the domain plugin will be notified with whole content of  table.
is possible to be notified with the updated row instead of the whole table?

Thanks.

**Comment by klihub** [comment]
I guess it would be technically possible but we settled on the current model for at least two reasons:
  1) You get atomically the current, up-to-date state of the watched table, without having to do anything extra.
  2) What you suggest should be easy to implement by always saving the latest table data at the end of every update notification callback, and checking the notification data against the previously saved one in the beginning of every notification callback.

**Comment by chengyi** [comment]
@klihub got it!  thanks
